/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface OracleRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_STAKE"
      | "approveSlasher"
      | "approvedSlasher"
      | "getOracles"
      | "isOracle"
      | "oracleAt"
      | "oracleCount"
      | "owner"
      | "register"
      | "revokeSlasher"
      | "slash"
      | "stakeOf"
      | "topUp"
      | "totalStake"
      | "transferOwnership"
      | "unregister"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OracleRegistered"
      | "OracleUnregistered"
      | "OwnerTransferred"
      | "Slashed"
      | "SlasherApproved"
      | "SlasherRevoked"
      | "StakeIncreased"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approveSlasher",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedSlasher",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOracles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "register", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeSlasher",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "slash",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "topUp", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unregister",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveSlasher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedSlasher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOracles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracleAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "oracleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeSlasher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "slash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "topUp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unregister", data: BytesLike): Result;
}

export namespace OracleRegisteredEvent {
  export type InputTuple = [oracle: AddressLike, stake: BigNumberish];
  export type OutputTuple = [oracle: string, stake: bigint];
  export interface OutputObject {
    oracle: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleUnregisteredEvent {
  export type InputTuple = [oracle: AddressLike, returned: BigNumberish];
  export type OutputTuple = [oracle: string, returned: bigint];
  export interface OutputObject {
    oracle: string;
    returned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerTransferredEvent {
  export type InputTuple = [prev: AddressLike, next: AddressLike];
  export type OutputTuple = [prev: string, next: string];
  export interface OutputObject {
    prev: string;
    next: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlashedEvent {
  export type InputTuple = [
    oracle: AddressLike,
    slasher: AddressLike,
    amount: BigNumberish,
    beneficiary: AddressLike
  ];
  export type OutputTuple = [
    oracle: string,
    slasher: string,
    amount: bigint,
    beneficiary: string
  ];
  export interface OutputObject {
    oracle: string;
    slasher: string;
    amount: bigint;
    beneficiary: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlasherApprovedEvent {
  export type InputTuple = [slasher: AddressLike];
  export type OutputTuple = [slasher: string];
  export interface OutputObject {
    slasher: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlasherRevokedEvent {
  export type InputTuple = [slasher: AddressLike];
  export type OutputTuple = [slasher: string];
  export interface OutputObject {
    slasher: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeIncreasedEvent {
  export type InputTuple = [oracle: AddressLike, newStake: BigNumberish];
  export type OutputTuple = [oracle: string, newStake: bigint];
  export interface OutputObject {
    oracle: string;
    newStake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OracleRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): OracleRegistry;
  waitForDeployment(): Promise<this>;

  interface: OracleRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  approveSlasher: TypedContractMethod<[s: AddressLike], [void], "nonpayable">;

  approvedSlasher: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getOracles: TypedContractMethod<[], [string[]], "view">;

  isOracle: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  oracleAt: TypedContractMethod<[i: BigNumberish], [string], "view">;

  oracleCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  register: TypedContractMethod<[], [void], "payable">;

  revokeSlasher: TypedContractMethod<[s: AddressLike], [void], "nonpayable">;

  slash: TypedContractMethod<
    [oracle: AddressLike, amount: BigNumberish, beneficiary: AddressLike],
    [bigint],
    "nonpayable"
  >;

  stakeOf: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  topUp: TypedContractMethod<[], [void], "payable">;

  totalStake: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [next: AddressLike],
    [void],
    "nonpayable"
  >;

  unregister: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveSlasher"
  ): TypedContractMethod<[s: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approvedSlasher"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getOracles"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isOracle"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "oracleAt"
  ): TypedContractMethod<[i: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "oracleCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "revokeSlasher"
  ): TypedContractMethod<[s: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slash"
  ): TypedContractMethod<
    [oracle: AddressLike, amount: BigNumberish, beneficiary: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakeOf"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "topUp"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "totalStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[next: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unregister"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "OracleRegistered"
  ): TypedContractEvent<
    OracleRegisteredEvent.InputTuple,
    OracleRegisteredEvent.OutputTuple,
    OracleRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OracleUnregistered"
  ): TypedContractEvent<
    OracleUnregisteredEvent.InputTuple,
    OracleUnregisteredEvent.OutputTuple,
    OracleUnregisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnerTransferred"
  ): TypedContractEvent<
    OwnerTransferredEvent.InputTuple,
    OwnerTransferredEvent.OutputTuple,
    OwnerTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Slashed"
  ): TypedContractEvent<
    SlashedEvent.InputTuple,
    SlashedEvent.OutputTuple,
    SlashedEvent.OutputObject
  >;
  getEvent(
    key: "SlasherApproved"
  ): TypedContractEvent<
    SlasherApprovedEvent.InputTuple,
    SlasherApprovedEvent.OutputTuple,
    SlasherApprovedEvent.OutputObject
  >;
  getEvent(
    key: "SlasherRevoked"
  ): TypedContractEvent<
    SlasherRevokedEvent.InputTuple,
    SlasherRevokedEvent.OutputTuple,
    SlasherRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StakeIncreased"
  ): TypedContractEvent<
    StakeIncreasedEvent.InputTuple,
    StakeIncreasedEvent.OutputTuple,
    StakeIncreasedEvent.OutputObject
  >;

  filters: {
    "OracleRegistered(address,uint256)": TypedContractEvent<
      OracleRegisteredEvent.InputTuple,
      OracleRegisteredEvent.OutputTuple,
      OracleRegisteredEvent.OutputObject
    >;
    OracleRegistered: TypedContractEvent<
      OracleRegisteredEvent.InputTuple,
      OracleRegisteredEvent.OutputTuple,
      OracleRegisteredEvent.OutputObject
    >;

    "OracleUnregistered(address,uint256)": TypedContractEvent<
      OracleUnregisteredEvent.InputTuple,
      OracleUnregisteredEvent.OutputTuple,
      OracleUnregisteredEvent.OutputObject
    >;
    OracleUnregistered: TypedContractEvent<
      OracleUnregisteredEvent.InputTuple,
      OracleUnregisteredEvent.OutputTuple,
      OracleUnregisteredEvent.OutputObject
    >;

    "OwnerTransferred(address,address)": TypedContractEvent<
      OwnerTransferredEvent.InputTuple,
      OwnerTransferredEvent.OutputTuple,
      OwnerTransferredEvent.OutputObject
    >;
    OwnerTransferred: TypedContractEvent<
      OwnerTransferredEvent.InputTuple,
      OwnerTransferredEvent.OutputTuple,
      OwnerTransferredEvent.OutputObject
    >;

    "Slashed(address,address,uint256,address)": TypedContractEvent<
      SlashedEvent.InputTuple,
      SlashedEvent.OutputTuple,
      SlashedEvent.OutputObject
    >;
    Slashed: TypedContractEvent<
      SlashedEvent.InputTuple,
      SlashedEvent.OutputTuple,
      SlashedEvent.OutputObject
    >;

    "SlasherApproved(address)": TypedContractEvent<
      SlasherApprovedEvent.InputTuple,
      SlasherApprovedEvent.OutputTuple,
      SlasherApprovedEvent.OutputObject
    >;
    SlasherApproved: TypedContractEvent<
      SlasherApprovedEvent.InputTuple,
      SlasherApprovedEvent.OutputTuple,
      SlasherApprovedEvent.OutputObject
    >;

    "SlasherRevoked(address)": TypedContractEvent<
      SlasherRevokedEvent.InputTuple,
      SlasherRevokedEvent.OutputTuple,
      SlasherRevokedEvent.OutputObject
    >;
    SlasherRevoked: TypedContractEvent<
      SlasherRevokedEvent.InputTuple,
      SlasherRevokedEvent.OutputTuple,
      SlasherRevokedEvent.OutputObject
    >;

    "StakeIncreased(address,uint256)": TypedContractEvent<
      StakeIncreasedEvent.InputTuple,
      StakeIncreasedEvent.OutputTuple,
      StakeIncreasedEvent.OutputObject
    >;
    StakeIncreased: TypedContractEvent<
      StakeIncreasedEvent.InputTuple,
      StakeIncreasedEvent.OutputTuple,
      StakeIncreasedEvent.OutputObject
    >;
  };
}
