/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISPUTE_BOND"
      | "DISPUTE_WINDOW"
      | "PROPOSAL_BOND"
      | "VOTE_WINDOW"
      | "claimDisputerBond"
      | "claimOracleReward"
      | "claimProposerBond"
      | "claimWinnings"
      | "claimed"
      | "createMarket"
      | "disputeProposal"
      | "finalizeMarket"
      | "getVoters"
      | "marketCount"
      | "markets"
      | "noStakes"
      | "oracleClaimed"
      | "oracleVote"
      | "oracleVoteWeight"
      | "proposeOutcome"
      | "registry"
      | "stakeNo"
      | "stakeYes"
      | "voteOnDispute"
      | "voterCount"
      | "yesStakes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Claimed"
      | "Disputed"
      | "DisputerBondClaimed"
      | "MarketCreated"
      | "MarketFinalized"
      | "OracleRewardClaimed"
      | "OracleVoted"
      | "Proposed"
      | "ProposerBondClaimed"
      | "Staked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISPUTE_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISPUTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSAL_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimDisputerBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimOracleReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimProposerBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "noStakes",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleClaimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleVote",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleVoteWeight",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeOutcome",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "stakeNo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeYes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteOnDispute",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voterCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "yesStakes",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DISPUTE_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISPUTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSAL_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDisputerBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimOracleReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimProposerBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVoters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "noStakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "oracleClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracleVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "oracleVoteWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeNo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeYes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteOnDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voterCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yesStakes", data: BytesLike): Result;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [marketId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    disputer: AddressLike,
    voteDeadline: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    disputer: string,
    voteDeadline: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    disputer: string;
    voteDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputerBondClaimedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    disputer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    disputer: string,
    amount: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    disputer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    creator: AddressLike,
    question: string,
    tradingDeadline: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    creator: string,
    question: string,
    tradingDeadline: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    creator: string;
    question: string;
    tradingDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketFinalizedEvent {
  export type InputTuple = [marketId: BigNumberish, result: BigNumberish];
  export type OutputTuple = [marketId: bigint, result: bigint];
  export interface OutputObject {
    marketId: bigint;
    result: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleRewardClaimedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    oracle: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [marketId: bigint, oracle: string, amount: bigint];
  export interface OutputObject {
    marketId: bigint;
    oracle: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleVotedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    oracle: AddressLike,
    outcome: BigNumberish,
    weight: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    oracle: string,
    outcome: bigint,
    weight: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    oracle: string;
    outcome: bigint;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    proposer: AddressLike,
    outcome: BigNumberish,
    disputeDeadline: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    proposer: string,
    outcome: bigint,
    disputeDeadline: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    proposer: string;
    outcome: bigint;
    disputeDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposerBondClaimedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    proposer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    proposer: string,
    amount: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    proposer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    isYes: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    user: string,
    isYes: boolean,
    amount: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    isYes: boolean;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISPUTE_BOND: TypedContractMethod<[], [bigint], "view">;

  DISPUTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  PROPOSAL_BOND: TypedContractMethod<[], [bigint], "view">;

  VOTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  claimDisputerBond: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimOracleReward: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimProposerBond: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimWinnings: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  createMarket: TypedContractMethod<
    [
      question: string,
      tradingDeadline: BigNumberish,
      proposalDeadline: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  disputeProposal: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "payable"
  >;

  finalizeMarket: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getVoters: TypedContractMethod<[marketId: BigNumberish], [string[]], "view">;

  marketCount: TypedContractMethod<[], [bigint], "view">;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        creator: string;
        question: string;
        tradingDeadline: bigint;
        proposalDeadline: bigint;
        disputeDeadline: bigint;
        voteDeadline: bigint;
        totalYesStake: bigint;
        totalNoStake: bigint;
        creatorBond: bigint;
        state: bigint;
        proposedOutcome: bigint;
        result: bigint;
        proposer: string;
        disputer: string;
        yesVoteWeight: bigint;
        noVoteWeight: bigint;
        invalidVoteWeight: bigint;
        slashPool: bigint;
        winningVoteWeight: bigint;
        proposerBondClaimed: boolean;
        disputerBondClaimed: boolean;
      }
    ],
    "view"
  >;

  noStakes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  oracleClaimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  oracleVote: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  oracleVoteWeight: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  proposeOutcome: TypedContractMethod<
    [marketId: BigNumberish, outcome: BigNumberish],
    [void],
    "payable"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  stakeNo: TypedContractMethod<[marketId: BigNumberish], [void], "payable">;

  stakeYes: TypedContractMethod<[marketId: BigNumberish], [void], "payable">;

  voteOnDispute: TypedContractMethod<
    [marketId: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  voterCount: TypedContractMethod<[marketId: BigNumberish], [bigint], "view">;

  yesStakes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISPUTE_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DISPUTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROPOSAL_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimDisputerBond"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimOracleReward"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimProposerBond"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWinnings"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      question: string,
      tradingDeadline: BigNumberish,
      proposalDeadline: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "disputeProposal"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "finalizeMarket"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getVoters"
  ): TypedContractMethod<[marketId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "marketCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        creator: string;
        question: string;
        tradingDeadline: bigint;
        proposalDeadline: bigint;
        disputeDeadline: bigint;
        voteDeadline: bigint;
        totalYesStake: bigint;
        totalNoStake: bigint;
        creatorBond: bigint;
        state: bigint;
        proposedOutcome: bigint;
        result: bigint;
        proposer: string;
        disputer: string;
        yesVoteWeight: bigint;
        noVoteWeight: bigint;
        invalidVoteWeight: bigint;
        slashPool: bigint;
        winningVoteWeight: bigint;
        proposerBondClaimed: boolean;
        disputerBondClaimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "noStakes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracleClaimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracleVote"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracleVoteWeight"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposeOutcome"
  ): TypedContractMethod<
    [marketId: BigNumberish, outcome: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stakeNo"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "stakeYes"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "voteOnDispute"
  ): TypedContractMethod<
    [marketId: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voterCount"
  ): TypedContractMethod<[marketId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "yesStakes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Disputed"
  ): TypedContractEvent<
    DisputedEvent.InputTuple,
    DisputedEvent.OutputTuple,
    DisputedEvent.OutputObject
  >;
  getEvent(
    key: "DisputerBondClaimed"
  ): TypedContractEvent<
    DisputerBondClaimedEvent.InputTuple,
    DisputerBondClaimedEvent.OutputTuple,
    DisputerBondClaimedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketFinalized"
  ): TypedContractEvent<
    MarketFinalizedEvent.InputTuple,
    MarketFinalizedEvent.OutputTuple,
    MarketFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "OracleRewardClaimed"
  ): TypedContractEvent<
    OracleRewardClaimedEvent.InputTuple,
    OracleRewardClaimedEvent.OutputTuple,
    OracleRewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "OracleVoted"
  ): TypedContractEvent<
    OracleVotedEvent.InputTuple,
    OracleVotedEvent.OutputTuple,
    OracleVotedEvent.OutputObject
  >;
  getEvent(
    key: "Proposed"
  ): TypedContractEvent<
    ProposedEvent.InputTuple,
    ProposedEvent.OutputTuple,
    ProposedEvent.OutputObject
  >;
  getEvent(
    key: "ProposerBondClaimed"
  ): TypedContractEvent<
    ProposerBondClaimedEvent.InputTuple,
    ProposerBondClaimedEvent.OutputTuple,
    ProposerBondClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;

  filters: {
    "Claimed(uint256,address,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "Disputed(uint256,address,uint256)": TypedContractEvent<
      DisputedEvent.InputTuple,
      DisputedEvent.OutputTuple,
      DisputedEvent.OutputObject
    >;
    Disputed: TypedContractEvent<
      DisputedEvent.InputTuple,
      DisputedEvent.OutputTuple,
      DisputedEvent.OutputObject
    >;

    "DisputerBondClaimed(uint256,address,uint256)": TypedContractEvent<
      DisputerBondClaimedEvent.InputTuple,
      DisputerBondClaimedEvent.OutputTuple,
      DisputerBondClaimedEvent.OutputObject
    >;
    DisputerBondClaimed: TypedContractEvent<
      DisputerBondClaimedEvent.InputTuple,
      DisputerBondClaimedEvent.OutputTuple,
      DisputerBondClaimedEvent.OutputObject
    >;

    "MarketCreated(uint256,address,string,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketFinalized(uint256,uint8)": TypedContractEvent<
      MarketFinalizedEvent.InputTuple,
      MarketFinalizedEvent.OutputTuple,
      MarketFinalizedEvent.OutputObject
    >;
    MarketFinalized: TypedContractEvent<
      MarketFinalizedEvent.InputTuple,
      MarketFinalizedEvent.OutputTuple,
      MarketFinalizedEvent.OutputObject
    >;

    "OracleRewardClaimed(uint256,address,uint256)": TypedContractEvent<
      OracleRewardClaimedEvent.InputTuple,
      OracleRewardClaimedEvent.OutputTuple,
      OracleRewardClaimedEvent.OutputObject
    >;
    OracleRewardClaimed: TypedContractEvent<
      OracleRewardClaimedEvent.InputTuple,
      OracleRewardClaimedEvent.OutputTuple,
      OracleRewardClaimedEvent.OutputObject
    >;

    "OracleVoted(uint256,address,uint8,uint256)": TypedContractEvent<
      OracleVotedEvent.InputTuple,
      OracleVotedEvent.OutputTuple,
      OracleVotedEvent.OutputObject
    >;
    OracleVoted: TypedContractEvent<
      OracleVotedEvent.InputTuple,
      OracleVotedEvent.OutputTuple,
      OracleVotedEvent.OutputObject
    >;

    "Proposed(uint256,address,uint8,uint256)": TypedContractEvent<
      ProposedEvent.InputTuple,
      ProposedEvent.OutputTuple,
      ProposedEvent.OutputObject
    >;
    Proposed: TypedContractEvent<
      ProposedEvent.InputTuple,
      ProposedEvent.OutputTuple,
      ProposedEvent.OutputObject
    >;

    "ProposerBondClaimed(uint256,address,uint256)": TypedContractEvent<
      ProposerBondClaimedEvent.InputTuple,
      ProposerBondClaimedEvent.OutputTuple,
      ProposerBondClaimedEvent.OutputObject
    >;
    ProposerBondClaimed: TypedContractEvent<
      ProposerBondClaimedEvent.InputTuple,
      ProposerBondClaimedEvent.OutputTuple,
      ProposerBondClaimedEvent.OutputObject
    >;

    "Staked(uint256,address,bool,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
  };
}
