/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "autoResolve"
      | "claimDisputerBond"
      | "claimOracleReward"
      | "claimProposerBond"
      | "claimWinnings"
      | "createMarket"
      | "createPriceMarket"
      | "disputeProposal"
      | "finalizeMarket"
      | "proposeOutcome"
      | "stakeNo"
      | "stakeYes"
      | "voteOnDispute"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "autoResolve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDisputerBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimOracleReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimProposerBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPriceMarket",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeOutcome",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeNo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeYes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteOnDispute",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "autoResolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDisputerBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimOracleReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimProposerBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPriceMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakeNo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeYes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteOnDispute",
    data: BytesLike
  ): Result;
}

export interface IPredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): IPredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: IPredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  autoResolve: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimDisputerBond: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimOracleReward: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimProposerBond: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimWinnings: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createMarket: TypedContractMethod<
    [
      question: string,
      metadataCID: string,
      tradingDeadline: BigNumberish,
      proposalDeadline: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  createPriceMarket: TypedContractMethod<
    [
      question: string,
      metadataCID: string,
      tradingDeadline: BigNumberish,
      proposalDeadline: BigNumberish,
      priceFeed: AddressLike,
      priceThreshold: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  disputeProposal: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "payable"
  >;

  finalizeMarket: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  proposeOutcome: TypedContractMethod<
    [marketId: BigNumberish, outcome: BigNumberish],
    [void],
    "payable"
  >;

  stakeNo: TypedContractMethod<[marketId: BigNumberish], [void], "payable">;

  stakeYes: TypedContractMethod<[marketId: BigNumberish], [void], "payable">;

  voteOnDispute: TypedContractMethod<
    [marketId: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "autoResolve"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimDisputerBond"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimOracleReward"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimProposerBond"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWinnings"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      question: string,
      metadataCID: string,
      tradingDeadline: BigNumberish,
      proposalDeadline: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createPriceMarket"
  ): TypedContractMethod<
    [
      question: string,
      metadataCID: string,
      tradingDeadline: BigNumberish,
      proposalDeadline: BigNumberish,
      priceFeed: AddressLike,
      priceThreshold: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "disputeProposal"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "finalizeMarket"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proposeOutcome"
  ): TypedContractMethod<
    [marketId: BigNumberish, outcome: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "stakeNo"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "stakeYes"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "voteOnDispute"
  ): TypedContractMethod<
    [marketId: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
